# Generated by Django 3.0.7 on 2020-06-11 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20200610_1804'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=50)),
                ('nbPerson', models.IntegerField()),
                ('email', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('message', models.TextField(null=True)),
                ('validate', models.TextField(default='false')),
            ],
            options={
                'verbose_name': 'Reservation',
                'ordering': ['validate', 'date'],
            },
        ),
    ]
