# Generated by Django 3.0.7 on 2020-06-11 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_reservation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['validate', 'date'], 'verbose_name': 'reservation'},
        ),
    ]
